namespace PORMS.Domain.Enums;

public enum OperationEventType
{
    WEATHER_FETCHED,
    RISK_ASSESSED,
    RISK_LEVEL_CHANGED,
    SOP_TRIGGERED,
    MODE_CHANGED,
    TASK_CREATED,
    ALERT_CREATED,
    ALERT_READ,
    THRESHOLD_UPDATED,
    SOP_RULE_UPDATED,
    SIMULATION_STARTED,
    SIMULATION_ENDED,
    MODE_OVERRIDDEN
}
