<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>681bb9b0-d0ec-4c52-b695-3d8502bd1e73</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Common\**" />
    <Content Remove="Common\**" />
    <EmbeddedResource Remove="Common\**" />
    <None Remove="Common\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PORMS.Application\PORMS.Application.csproj" />
    <ProjectReference Include="..\PORMS.Domain\PORMS.Domain.csproj" />
    <ProjectReference Include="..\PORMS.Infrastructure\PORMS.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
  </ItemGroup>
</Project>
